/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import query.jDlgCjrConsultaUsuarios;
import query.jDlgCjrConsultaCliente;
import query.jDlgCjrConsultaProduto;
import query.jDlgCjrConsultaFuncionario;
import query.jDlgCjrConsultaVenda;
/**
 *
 * @author Junior
 */
public class JFrmCjrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmCjrPrincipal() {
        initComponents();
        setTitle("Sistema de Vendas de Instrumentos Musicais");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jBntClientes = new javax.swing.JButton();
        jBntProduto = new javax.swing.JButton();
        jBntVendas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuFuncionarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        jMnuUsuariosConsulta = new javax.swing.JMenuItem();
        jMnuClientesConsulta = new javax.swing.JMenuItem();
        jMnuProdutoConsulta = new javax.swing.JMenuItem();
        jMnuFuncionarioConsulta = new javax.swing.JMenuItem();
        jMnuFuncionarioConsulta1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/instrumentaliza logo vendas.jpg"))); // NOI18N

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        jBntClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        jBntClientes.setFocusable(false);
        jBntClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntClientes);

        jBntProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos_2.png"))); // NOI18N
        jBntProduto.setFocusable(false);
        jBntProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntProdutoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntProduto);

        jBntVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jBntVendas.setFocusable(false);
        jBntVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntVendas);

        jMnuPrincipal.setText("Principal");
        jMnuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPrincipalActionPerformed(evt);
            }
        });

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuUsuarios);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos_2.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuProdutos);

        jMnuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        jMnuFuncionarios.setText("Funcionarios");
        jMnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuFuncionarios);
        jMnuPrincipal.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuSair);

        jMenuBar1.add(jMnuPrincipal);

        jMnuMovimento.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsultas.setText("Consultas ");

        jMnuUsuariosConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuariosConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_preto.png"))); // NOI18N
        jMnuUsuariosConsulta.setText("Usuarios");
        jMnuUsuariosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuUsuariosConsulta);

        jMnuClientesConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientesConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_preto.png"))); // NOI18N
        jMnuClientesConsulta.setText("Clientes");
        jMnuClientesConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuClientesConsulta);

        jMnuProdutoConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutoConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_preto.png"))); // NOI18N
        jMnuProdutoConsulta.setText("Produto");
        jMnuProdutoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutoConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuProdutoConsulta);

        jMnuFuncionarioConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarioConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_preto.png"))); // NOI18N
        jMnuFuncionarioConsulta.setText("Funcionario");
        jMnuFuncionarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionarioConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuFuncionarioConsulta);

        jMnuFuncionarioConsulta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarioConsulta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_preto.png"))); // NOI18N
        jMnuFuncionarioConsulta1.setText("Vendas");
        jMnuFuncionarioConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionarioConsulta1ActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuFuncionarioConsulta1);

        jMenuBar1.add(jMnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        jDlgCjrCliente jDlgCjrClientes = new jDlgCjrCliente(null, true);
        jDlgCjrClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        jDlgCjrUsuarios jDlgCjrUsuarios = new jDlgCjrUsuarios(null, true);
        jDlgCjrUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        jDlgCjrVenda jDlgCjrVenda1 = new jDlgCjrVenda(null, true);
        jDlgCjrVenda1.setVisible(true);
        
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        jDlgCjrProdutoNovo jDlgCjrProdutoNovo = new jDlgCjrProdutoNovo(null, true);
        jDlgCjrProdutoNovo.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionariosActionPerformed
        // TODO add your handling code here:
        jDlgCjrFuncionarioNovo jDlgCjrFuncionarioNovo = new jDlgCjrFuncionarioNovo(null, true);
        jDlgCjrFuncionarioNovo.setVisible(true);
    }//GEN-LAST:event_jMnuFuncionariosActionPerformed

    private void jMnuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuPrincipalActionPerformed

    private void jMnuUsuariosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosConsultaActionPerformed
        // TODO add your handling code here:
        jDlgCjrConsultaUsuarios jDlgCjrConsultaUsuarios = new jDlgCjrConsultaUsuarios(null, true);
        jDlgCjrConsultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosConsultaActionPerformed

    private void jBntClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntClientesActionPerformed
        // TODO add your handling code here:
        jDlgCjrCliente jDlgCjrCliente1 = new jDlgCjrCliente(null, true);
        jDlgCjrCliente1.setVisible(true);
    }//GEN-LAST:event_jBntClientesActionPerformed

    private void jBntProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntProdutoActionPerformed
        // TODO add your handling code here:
        jDlgCjrProdutoNovo jDlgCjrProdutoNovo1 = new jDlgCjrProdutoNovo(null, true);
        jDlgCjrProdutoNovo1.setVisible(true);
    }//GEN-LAST:event_jBntProdutoActionPerformed

    private void jBntVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntVendasActionPerformed
        // TODO add your handling code here:
        jDlgCjrVenda jDlgCjrVenda1 = new jDlgCjrVenda(null, true);
        jDlgCjrVenda1.setVisible(true);
    }//GEN-LAST:event_jBntVendasActionPerformed

    private void jMnuClientesConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesConsultaActionPerformed
        // TODO add your handling code here:
        jDlgCjrConsultaCliente jDlgCjrConsultaCliente1 = new jDlgCjrConsultaCliente(null, true);
        jDlgCjrConsultaCliente1.setVisible(true);
    }//GEN-LAST:event_jMnuClientesConsultaActionPerformed

    private void jMnuProdutoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutoConsultaActionPerformed
        // TODO add your handling code here:
        jDlgCjrConsultaProduto jDlgCjrConsultaProduto1 = new jDlgCjrConsultaProduto(null, true);
        jDlgCjrConsultaProduto1.setVisible(true);
    }//GEN-LAST:event_jMnuProdutoConsultaActionPerformed

    private void jMnuFuncionarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionarioConsultaActionPerformed
        // TODO add your handling code here:
        jDlgCjrConsultaFuncionario jDlgCjrConsultaFuncionario1 = new jDlgCjrConsultaFuncionario(null, true);
        jDlgCjrConsultaFuncionario1.setVisible(true);
    }//GEN-LAST:event_jMnuFuncionarioConsultaActionPerformed

    private void jMnuFuncionarioConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionarioConsulta1ActionPerformed
        // TODO add your handling code here:
        jDlgCjrConsultaVenda jDlgCjrConsultaVenda1 = new jDlgCjrConsultaVenda(null, true);
        jDlgCjrConsultaVenda1.setVisible(true);
    }//GEN-LAST:event_jMnuFuncionarioConsulta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmCjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmCjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmCjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmCjrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntClientes;
    private javax.swing.JButton jBntProduto;
    private javax.swing.JButton jBntVendas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuClientesConsulta;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenuItem jMnuFuncionarioConsulta;
    private javax.swing.JMenuItem jMnuFuncionarioConsulta1;
    private javax.swing.JMenuItem jMnuFuncionarios;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuPrincipal;
    private javax.swing.JMenuItem jMnuProdutoConsulta;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuUsuariosConsulta;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
