package bean;
// Generated Sep 20, 2023 3:04:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CjrFuncionario generated by hbm2java
 */
@Entity
@Table(name="cjr_funcionario"
    ,catalog="db_claudio_elizeche"
)
public class CjrFuncionario  implements java.io.Serializable {


     private int cjrIdFuncionario;
     private String cjrNome;
     private String cjrEndereco;
     private String cjrCpf;
     private String cjrApelido;
     

    public CjrFuncionario() {
    }

	
    public CjrFuncionario(String cjrNome, String cjrEndereco, String cjrCpf, String cjrApelido) {
        this.cjrNome = cjrNome;
        this.cjrEndereco = cjrEndereco;
        this.cjrCpf = cjrCpf;
        this.cjrApelido = cjrApelido;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cjr_idFuncionario", unique=true, nullable=false)
    public int getCjrIdFuncionario() {
        return this.cjrIdFuncionario;
    }
    
    public void setCjrIdFuncionario(int cjrIdFuncionario) {
        this.cjrIdFuncionario = cjrIdFuncionario;
    }

    
    @Column(name="cjr_nome", nullable=false, length=45)
    public String getCjrNome() {
        return this.cjrNome;
    }
    
    public void setCjrNome(String cjrNome) {
        this.cjrNome = cjrNome;
    }

    
    @Column(name="cjr_endereco", nullable=false, length=45)
    public String getCjrEndereco() {
        return this.cjrEndereco;
    }
    
    public void setCjrEndereco(String cjrEndereco) {
        this.cjrEndereco = cjrEndereco;
    }

    
    @Column(name="cjr_cpf", nullable=false, length=14)
    public String getCjrCpf() {
        return this.cjrCpf;
    }
    
    public void setCjrCpf(String cjrCpf) {
        this.cjrCpf = cjrCpf;
    }

    
    @Column(name="cjr_apelido", nullable=false, length=45)
    public String getCjrApelido() {
        return this.cjrApelido;
    }
    
    public void setCjrApelido(String cjrApelido) {
        this.cjrApelido = cjrApelido;
    }


}


