package bean;
// Generated Sep 20, 2023 3:04:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CjrVenda generated by hbm2java
 */
@Entity
@Table(name="cjr_venda"
    ,catalog="db_claudio_elizeche"
)
public class CjrVenda  implements java.io.Serializable {


     private Integer cjrIdVenda;
     private CjrCliente cjrCliente;
     private CjrFuncionario cjrFuncionario;
     private Date cjrDataVenda;
     private double cjrValorTotal;
     private String cjrQuantidadeVenda;    

    public CjrVenda() {
    }

	
    public CjrVenda(Date cjrDataVenda, double cjrValorTotal, String cjrQuantidadeVenda) {
        this.cjrDataVenda = cjrDataVenda;
        this.cjrValorTotal = cjrValorTotal;
        this.cjrQuantidadeVenda = cjrQuantidadeVenda;
    }
    public CjrVenda(CjrCliente cjrCliente, CjrFuncionario cjrFuncionario, Date cjrDataVenda, double cjrValorTotal, String cjrQuantidadeVenda) {
       this.cjrCliente = cjrCliente;
       this.cjrFuncionario = cjrFuncionario;
       this.cjrDataVenda = cjrDataVenda;
       this.cjrValorTotal = cjrValorTotal;
       this.cjrQuantidadeVenda = cjrQuantidadeVenda;

    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cjr_idVenda", unique=true, nullable=false)
    public Integer getCjrIdVenda() {
        return this.cjrIdVenda;
    }
    
    public void setCjrIdVenda(Integer cjrIdVenda) {
        this.cjrIdVenda = cjrIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cjr_cliente")
    public CjrCliente getCjrCliente() {
        return this.cjrCliente;
    }
    
    public void setCjrCliente(CjrCliente cjrCliente) {
        this.cjrCliente = cjrCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cjr_funcionario")
    public CjrFuncionario getCjrFuncionario() {
        return this.cjrFuncionario;
    }
    
    public void setCjrFuncionario(CjrFuncionario cjrFuncionario) {
        this.cjrFuncionario = cjrFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cjr_data_venda", nullable=false, length=19)
    public Date getCjrDataVenda() {
        return this.cjrDataVenda;
    }
    
    public void setCjrDataVenda(Date cjrDataVenda) {
        this.cjrDataVenda = cjrDataVenda;
    }

    
    @Column(name="cjr_valor_total", nullable=false, precision=10)
    public double getCjrValorTotal() {
        return this.cjrValorTotal;
    }
    
    public void setCjrValorTotal(double cjrValorTotal) {
        this.cjrValorTotal = cjrValorTotal;
    }

    
    @Column(name="cjr_quantidade_venda", nullable=false, length=45)
    public String getCjrQuantidadeVenda() {
        return this.cjrQuantidadeVenda;
    }
    
    public void setCjrQuantidadeVenda(String cjrQuantidadeVenda) {
        this.cjrQuantidadeVenda = cjrQuantidadeVenda;
    }
}


