package bean;
// Generated Sep 20, 2023 3:04:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CjrVendaProduto generated by hbm2java
 */
@Entity
@Table(name="cjr_venda_produto"
    ,catalog="db_claudio_elizeche"
)
public class CjrVendaProduto  implements java.io.Serializable {


     private Integer cjrIdVendaProduto;
     private CjrProduto cjrProduto;
     private CjrVenda cjrVenda;
     private int cjrQuantidade;
     private double cjrValorUnitario;

    public CjrVendaProduto() {
    }

	
    public CjrVendaProduto(int cjrQuantidade, double cjrValorUnitario) {
        this.cjrQuantidade = cjrQuantidade;
        this.cjrValorUnitario = cjrValorUnitario;
    }
    public CjrVendaProduto(CjrProduto cjrProduto, CjrVenda cjrVenda, int cjrQuantidade, double cjrValorUnitario) {
       this.cjrProduto = cjrProduto;
       this.cjrVenda = cjrVenda;
       this.cjrQuantidade = cjrQuantidade;
       this.cjrValorUnitario = cjrValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cjr_idVenda_produto", unique=true, nullable=false)
    public Integer getCjrIdVendaProduto() {
        return this.cjrIdVendaProduto;
    }
    
    public void setCjrIdVendaProduto(Integer cjrIdVendaProduto) {
        this.cjrIdVendaProduto = cjrIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cjr_produto")
    public CjrProduto getCjrProduto() {
        return this.cjrProduto;
    }
    
    public void setCjrProduto(CjrProduto cjrProduto) {
        this.cjrProduto = cjrProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cjr_venda")
    public CjrVenda getCjrVenda() {
        return this.cjrVenda;
    }
    
    public void setCjrVenda(CjrVenda cjrVenda) {
        this.cjrVenda = cjrVenda;
    }

    
    @Column(name="cjr_quantidade", nullable=false)
    public int getCjrQuantidade() {
        return this.cjrQuantidade;
    }
    
    public void setCjrQuantidade(int cjrQuantidade) {
        this.cjrQuantidade = cjrQuantidade;
    }

    
    @Column(name="cjr_valor_unitario", nullable=false, precision=10)
    public double getCjrValorUnitario() {
        return this.cjrValorUnitario;
    }
    
    public void setCjrValorUnitario(double cjrValorUnitario) {
        this.cjrValorUnitario = cjrValorUnitario;
    }

    @Override
    public String toString() {
        return super.toString(); //To change body of generated methods, choose Tools | Templates.
    }




}


